from pathlib import Path

import pandas as pd
from openpyxl import Workbook


BASE_DIR = Path(__file__).resolve().parent
SAMPLE_DATA_DIR = BASE_DIR / "sample_data"
TEMPLATES_DIR = BASE_DIR / "templates"


def create_dummy_master_excel(path: Path) -> None:
    register_data = [
        {
            "Sr.No.": 1,
            "Code": "EMP001",
            "Employee Name": "Aarav Sharma",
            "Department": "HR",
            "Designation": "Manager",
            "Branch": "Maharashtra",
            "Unit": "Mumbai-Powai",
            "Grade": "G1",
            "Status": "Active",
            "Gender": "Male",
            "Join Date": "2020-01-10",
            "Fixed Basic": 80000,
            "Net Paid": 95000,
            "PF Employer": 1200,
            "ESIC Employer": 300,
            "CTC": 110000,
            "Bank IFSC Code": "SBIN0001234",
            "Bank UPL": 50000,
            "UAN No": "100123456789",
            "PF No": "PF001",
            "Month Year": "2026-07",
        },
        {
            "Sr.No.": 2,
            "Code": "EMP002",
            "Employee Name": "Diya Patel",
            "Department": "Finance",
            "Designation": "Analyst",
            "Branch": "Maharashtra",
            "Unit": "Mumbai-Borivali",
            "Grade": "G2",
            "Status": "Active",
            "Gender": "Female",
            "Join Date": "2021-03-15",
            "Fixed Basic": 65000,
            "Net Paid": 78000,
            "PF Employer": 1000,
            "ESIC Employer": 250,
            "CTC": 90000,
            "Bank IFSC Code": "HDFC0005678",
            "Bank UPL": 40000,
            "UAN No": "100987654321",
            "PF No": "PF002",
            "Month Year": "2026-07",
        },
        {
            "Sr.No.": 3,
            "Code": "EMP003",
            "Employee Name": "Rohan Verma",
            "Department": "Operations",
            "Designation": "Supervisor",
            "Branch": "Karnataka",
            "Unit": "Bangalore Bellandur",
            "Grade": "G3",
            "Status": "Active",
            "Gender": "Male",
            "Join Date": "2019-11-20",
            "Fixed Basic": 72000,
            "Net Paid": 86000,
            "PF Employer": 1100,
            "ESIC Employer": 280,
            "CTC": 98000,
            "Bank IFSC Code": "ICIC0002222",
            "Bank UPL": 45000,
            "UAN No": "100456789123",
            "PF No": "PF003",
            "Month Year": "2026-07",
        },
        {
            "Sr.No.": 4,
            "Code": "EMP004",
            "Employee Name": "Priya Kapoor",
            "Department": "Sales",
            "Designation": "Executive",
            "Branch": "Karnataka",
            "Unit": "Bangalore Orion Mall",
            "Grade": "G2",
            "Status": "Active",
            "Gender": "Female",
            "Join Date": "2022-02-01",
            "Fixed Basic": 60000,
            "Net Paid": 72000,
            "PF Employer": 950,
            "ESIC Employer": 240,
            "CTC": 88000,
            "Bank IFSC Code": "AXIS0003333",
            "Bank UPL": 38000,
            "UAN No": "100234567890",
            "PF No": "PF004",
            "Month Year": "2026-07",
        },
        {
            "Sr.No.": 5,
            "Code": "EMP005",
            "Employee Name": "Neha Singh",
            "Department": "Operations",
            "Designation": "Coordinator",
            "Branch": "Haryana",
            "Unit": "Gurugram",
            "Grade": "G3",
            "Status": "Active",
            "Gender": "Female",
            "Join Date": "2021-08-12",
            "Fixed Basic": 58000,
            "Net Paid": 70000,
            "PF Employer": 920,
            "ESIC Employer": 230,
            "CTC": 86000,
            "Bank IFSC Code": "PNB0004444",
            "Bank UPL": 36000,
            "UAN No": "100345678901",
            "PF No": "PF005",
            "Month Year": "2026-07",
        },
    ]

    leave_data = [
        {"Employee Code": "EMP001", "Employee Name": "Aarav Sharma", "Leave Type": "CL", "For Month": "2026-07", "Opening": 0, "Accrued": 2, "Monthly Increment": 0, "Used": 1, "Encashment": 0, "Closing": 1},
        {"Employee Code": "EMP002", "Employee Name": "Diya Patel", "Leave Type": "PL", "For Month": "2026-07", "Opening": 1, "Accrued": 1, "Monthly Increment": 0, "Used": 0, "Encashment": 0, "Closing": 2},
        {"Employee Code": "EMP003", "Employee Name": "Rohan Verma", "Leave Type": "CL", "For Month": "2026-07", "Opening": 1, "Accrued": 2, "Monthly Increment": 0, "Used": 2, "Encashment": 0, "Closing": 1},
        {"Employee Code": "EMP004", "Employee Name": "Priya Kapoor", "Leave Type": "PL", "For Month": "2026-07", "Opening": 2, "Accrued": 1, "Monthly Increment": 0, "Used": 1, "Encashment": 0, "Closing": 2},
        {"Employee Code": "EMP005", "Employee Name": "Neha Singh", "Leave Type": "CL", "For Month": "2026-07", "Opening": 0, "Accrued": 2, "Monthly Increment": 0, "Used": 1, "Encashment": 0, "Closing": 1},
    ]

    compliance_master = [
        {
            "Sr.No.": 1,
            "Code": "EMP001",
            "Employee Name": "Aarav Sharma",
            "Birth Date": "1990-04-12",
            "Join Date": "2020-01-10",
            "Last Working Date": "",
            "Status": "Active",
            "Gender": "Male",
            "Unit": "Mumbai-Powai",
            "Department": "HR",
            "Designation": "Manager",
            "ESIC Old No": "ESIC001",
            "UAN No": "100123456789",
            "PF No": "PF001",
            "Aadhar Number": "123412341234",
            "PAN": "ABCDE1234F",
            "Father Name": "Ravi Sharma",
            "Marital Status": "Married",
            "Mobile": "9999999999",
            "Bank Name": "SBI",
            "Number": "123456789012",
        },
        {
            "Sr.No.": 2,
            "Code": "EMP002",
            "Employee Name": "Diya Patel",
            "Birth Date": "1993-09-22",
            "Join Date": "2021-03-15",
            "Last Working Date": "",
            "Status": "Active",
            "Gender": "Female",
            "Unit": "Mumbai-Borivali",
            "Department": "Finance",
            "Designation": "Analyst",
            "ESIC Old No": "ESIC002",
            "UAN No": "100987654321",
            "PF No": "PF002",
            "Aadhar Number": "223422341234",
            "PAN": "FGHIJ5678K",
            "Father Name": "Nilesh Patel",
            "Marital Status": "Single",
            "Mobile": "8888888888",
            "Bank Name": "HDFC",
            "Number": "234567890123",
        },
        {
            "Sr.No.": 3,
            "Code": "EMP003",
            "Employee Name": "Rohan Verma",
            "Birth Date": "1988-06-05",
            "Join Date": "2019-11-20",
            "Last Working Date": "",
            "Status": "Active",
            "Gender": "Male",
            "Unit": "Bangalore Bellandur",
            "Department": "Operations",
            "Designation": "Supervisor",
            "ESIC Old No": "ESIC003",
            "UAN No": "100456789123",
            "PF No": "PF003",
            "Aadhar Number": "323412349876",
            "PAN": "LMNOP9012Q",
            "Father Name": "Suresh Verma",
            "Marital Status": "Married",
            "Mobile": "7777777777",
            "Bank Name": "ICICI",
            "Number": "345678901234",
        },
        {
            "Sr.No.": 4,
            "Code": "EMP004",
            "Employee Name": "Priya Kapoor",
            "Birth Date": "1995-12-04",
            "Join Date": "2022-02-01",
            "Last Working Date": "",
            "Status": "Active",
            "Gender": "Female",
            "Unit": "Bangalore Orion Mall",
            "Department": "Sales",
            "Designation": "Executive",
            "ESIC Old No": "ESIC004",
            "UAN No": "100234567890",
            "PF No": "PF004",
            "Aadhar Number": "423412341234",
            "PAN": "QRSTU3456V",
            "Father Name": "Ajay Kapoor",
            "Marital Status": "Single",
            "Mobile": "6666666666",
            "Bank Name": "AXIS",
            "Number": "456789012345",
        },
        {
            "Sr.No.": 5,
            "Code": "EMP005",
            "Employee Name": "Neha Singh",
            "Birth Date": "1992-07-18",
            "Join Date": "2021-08-12",
            "Last Working Date": "",
            "Status": "Active",
            "Gender": "Female",
            "Unit": "Gurugram",
            "Department": "Operations",
            "Designation": "Coordinator",
            "ESIC Old No": "ESIC005",
            "UAN No": "100345678901",
            "PF No": "PF005",
            "Aadhar Number": "523412341234",
            "PAN": "VWXYZ6789A",
            "Father Name": "Mohan Singh",
            "Marital Status": "Married",
            "Mobile": "5555555555",
            "Bank Name": "PNB",
            "Number": "567890123456",
        },
    ]

    unit_mast = [
        {
            "Sr.No.": 1,
            "Code": "EMP001",
            "State": "Maharashtra",
            "Unit": "Mumbai-Powai",
            "Type": "Outlet",
            "Address": "Powai, Mumbai",
            "From": "08:00",
            "To": "17:00",
            "Rest From": "13:00",
            "Rest To": "14:00",
            "Duty Hours": "8",
            "Weekly Off": "Sunday",
        },
        {
            "Sr.No.": 2,
            "Code": "EMP002",
            "State": "Maharashtra",
            "Unit": "Mumbai-Borivali",
            "Type": "Store",
            "Address": "Borivali, Mumbai",
            "From": "09:00",
            "To": "18:00",
            "Rest From": "13:00",
            "Rest To": "14:00",
            "Duty Hours": "8",
            "Weekly Off": "Saturday",
        },
        {
            "Sr.No.": 3,
            "Code": "EMP003",
            "State": "Karnataka",
            "Unit": "Bangalore Bellandur",
            "Type": "Outlet",
            "Address": "Bellandur, Bengaluru",
            "From": "08:30",
            "To": "17:30",
            "Rest From": "13:30",
            "Rest To": "14:30",
            "Duty Hours": "8",
            "Weekly Off": "Sunday",
        },
        {
            "Sr.No.": 4,
            "Code": "EMP004",
            "State": "Karnataka",
            "Unit": "Bangalore Orion Mall",
            "Type": "Store",
            "Address": "Orion Mall, Bengaluru",
            "From": "09:30",
            "To": "18:30",
            "Rest From": "14:00",
            "Rest To": "15:00",
            "Duty Hours": "8",
            "Weekly Off": "Saturday",
        },
        {
            "Sr.No.": 5,
            "Code": "EMP005",
            "State": "Haryana",
            "Unit": "Gurugram",
            "Type": "Head Office",
            "Address": "Gurugram HQ",
            "From": "08:00",
            "To": "17:00",
            "Rest From": "13:00",
            "Rest To": "14:00",
            "Duty Hours": "8",
            "Weekly Off": "Sunday",
        },
    ]

    attendance = [
        {"Employee Code": "EMP001", "Employee Name": "Aarav Sharma", "Join Date": "2020-01-10", "Gender": "Male", "Department": "HR", "Designation": "Manager", "Unit": "Mumbai-Powai", "Desc": "Present", "1": 1, "2": 1, "3": 1, "4": 1, "5": 1, "6": 1, "7": 1, "8": 1, "9": 1, "10": 1, "TOTAL": 10, "Remarks": "Good"},
        {"Employee Code": "EMP002", "Employee Name": "Diya Patel", "Join Date": "2021-03-15", "Gender": "Female", "Department": "Finance", "Designation": "Analyst", "Unit": "Mumbai-Borivali", "Desc": "Present", "1": 1, "2": 1, "3": 1, "4": 1, "5": 1, "6": 1, "7": 1, "8": 1, "9": 1, "10": 1, "TOTAL": 10, "Remarks": "Excellent"},
        {"Employee Code": "EMP003", "Employee Name": "Rohan Verma", "Join Date": "2019-11-20", "Gender": "Male", "Department": "Operations", "Designation": "Supervisor", "Unit": "Bangalore Bellandur", "Desc": "Present", "1": 1, "2": 1, "3": 1, "4": 1, "5": 1, "6": 1, "7": 1, "8": 1, "9": 1, "10": 1, "TOTAL": 10, "Remarks": "Good"},
        {"Employee Code": "EMP004", "Employee Name": "Priya Kapoor", "Join Date": "2022-02-01", "Gender": "Female", "Department": "Sales", "Designation": "Executive", "Unit": "Bangalore Orion Mall", "Desc": "Present", "1": 1, "2": 1, "3": 1, "4": 1, "5": 1, "6": 1, "7": 1, "8": 1, "9": 1, "10": 1, "TOTAL": 10, "Remarks": "Excellent"},
        {"Employee Code": "EMP005", "Employee Name": "Neha Singh", "Join Date": "2021-08-12", "Gender": "Female", "Department": "Operations", "Designation": "Coordinator", "Unit": "Gurugram", "Desc": "Present", "1": 1, "2": 1, "3": 1, "4": 1, "5": 1, "6": 1, "7": 1, "8": 1, "9": 1, "10": 1, "TOTAL": 10, "Remarks": "Good"},
    ]

    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        pd.DataFrame(register_data).to_excel(writer, sheet_name="Register", index=False)
        pd.DataFrame(leave_data).to_excel(writer, sheet_name="Leave Data", index=False)
        pd.DataFrame(compliance_master).to_excel(writer, sheet_name="Compliance Master", index=False)
        pd.DataFrame(unit_mast).to_excel(writer, sheet_name="Unit Mast", index=False)
        pd.DataFrame(attendance).to_excel(writer, sheet_name="Attendance", index=False)


def create_blank_templates() -> None:
    template_specs = {
        "Form_A_Template.xlsx": [
            "Sr.no",
            "Code",
            "Name of Employee",
            "Father /Husband",
            "Working hrs. FROM",
            "Working hrs. TO",
            "Rest Interval - FROM",
            "Rest Interval - TO",
        ],
        "Form_C_Template.xlsx": [
            "SR.NO",
            "CODE",
            "Name of employee",
            "Father's/Husband's name",
            "Age/DOB",
            "Nature of work",
            "Date of appointment",
            "Spread-Over",
            "Interval for rest and meals",
            "Total Working Hour",
        ],
        "Form_D_Template.xlsx": [
            "SR.NO.",
            "Code",
            "Name of the Employee",
            "Father/ Husband",
            "Arrears from the last month",
            "Wage Month",
            "Wages Due",
            "Deduction",
            "Wages Earned",
            "Payments Made",
        ],
        "Form_E_Template.xlsx": [
            "Serial No.",
            "Code",
            "Name of employee",
            "Percentage%",
            "Wage Period",
            "Wages payable",
            "Amount deducted",
            "Date of deduction",
        ],
        "Form_V_Template.xlsx": [
            "Sl.No.",
            "Employee Code",
            "Name of Employee",
            "Father's / Husband's Name",
            "Sex",
            "Nature of work",
            "01",
            "02",
            "03",
            "04",
            "05",
            "TOTAL",
        ],
    }

    for file_name, headers in template_specs.items():
        workbook = Workbook()
        sheet = workbook.active
        sheet.title = "Sheet1"
        for row_idx in range(1, 11):
            for col_idx in range(1, len(headers) + 1):
                sheet.cell(row=row_idx, column=col_idx, value="")
        for col_idx, header in enumerate(headers, start=1):
            sheet.cell(row=10, column=col_idx, value=header)
        output_path = TEMPLATES_DIR / file_name
        workbook.save(output_path)


def main() -> None:
    SAMPLE_DATA_DIR.mkdir(parents=True, exist_ok=True)
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    create_dummy_master_excel(SAMPLE_DATA_DIR / "dummy_master_compliance.xlsx")
    create_blank_templates()
    print("Created sample_data and templates successfully.")


if __name__ == "__main__":
    main()
