# Main Master Data File URL 
EXCEL_FILE_URL = "https://docs.google.com/spreadsheets/d/1YNzVafCcLY6mDFQGxWyrU9Uf549U3iTU/export?format=xlsx"

# Chandigarh Form Templates
[templates.Chandigarh]
"Form A" = "https://docs.google.com/spreadsheets/d/1SGixdFPegR-mjMEl82P2Abg0vZU0XzzX/export?format=xlsx"
"Form C" = "https://docs.google.com/spreadsheets/d/102kojGB-EPMdicYUrtjI6d_RKZsHPy4C/export?format=xlsx"
"Form D" = "https://docs.google.com/spreadsheets/d/1VIM2nwG-bOP81MloYGPSQnAoZDRtaVaS/export?format=xlsx"
"Form E" = "https://docs.google.com/spreadsheets/d/1sabgiKYUdlSEG52eIdyTKHYf_KSvWfnJ/export?format=xlsx"
"Form IV" = "https://docs.google.com/spreadsheets/d/1hjlNt-i1lL7lPiy_GR_ownDds7mS8ITa/export?format=xlsx"
"Form V" = "https://docs.google.com/spreadsheets/d/11q6HGD6LYYjp2V2QwSbBY8JcGsFlPzR9/export?format=xlsx"